### ISSUE TITLE
Doesn't seem to be able to import packages with their own relative imports(?)

### ISSUE THREAD

**Issue by dabrahams** [klesun/ts-browser#22] opened 2021-11-26 21:12 UTC
I copied the [capsize project](https://seek-oss.github.io/capsize/) into my site at `/assets/js/capsize` and tried to 

```js
loadModule('/assets/js/capsize/packages/core/src/index');
```

but it seemed to choke on that file's relative import:

```ts
export { createStyleObject } from './createStyleObject';
```

<img width="544" alt="image" src="https://user-images.githubusercontent.com/44065/143626362-c99c877c-43d1-4a83-8fa3-a177deef35a3.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/44065/143626079-76a4dedd-d3d9-481d-9e8e-69cd0b82910b.png">

**Comment by klesun** [comment] 2022-05-21 14:59
Thanks for the report!
This is a duplicate of https://github.com/klesun/ts-browser/issues/18

**Closed as completed by klesun** 2022-05-21 14:59 UTC
